# Blog settings
permalink: /blog/:title


# My variables
name: ./

google_verification: null
title: ./
email: oktay.sabak@skteknoloji.com.tr
description: > # this means to ignore newlines until "baseurl:"
  Hello friend! 
baseurl: "/posts" # the subpath of your site, e.g. /blog
url: "https://oktaysabak.github.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: oktaysabak
github_username:  oktaysabak

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
